---
- name: Ensure openvpn package
  ansible.builtin.package:
    name: openvpn
    state: present
  become: true
  become_user: root

- name: Deploy ssh restart script
  ansible.builtin.copy:
    src: restart_ssh.sh
    dest: /etc/openvpn/restart_ssh.sh
    owner: root
    group: root
    mode: "0755"
  become: true
  become_user: root

- name: Put config in place
  ansible.builtin.template:
    src: openvpn_client_config.conf.jinja2
    dest: "/etc/openvpn/{{ openvpn_client_filename }}.conf"
    owner: root
    group: root
    mode: "0640"
  notify: Restart openvpn
  become: true
  become_user: root

- name: Enable and start openvpn systemd unit
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: "openvpn@{{ openvpn_client_filename }}.service"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
