---
- name: Restart openvpn
  ansible.builtin.systemd:
    state: restarted
    name: "openvpn@{{ openvpn_client_filename }}.service"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
